<?php
$this->assets->outputCss();
?>
<h1>Lorem ipsum dolor sit amet.</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium rem odit, iusto asperiores veniam tempora enim, culpa explicabo in odio facilis ex adipisci suscipit amet quos fugit eaque. Cum, minima.
    Voluptatem ipsam ex cum porro neque ab, nesciunt, aspernatur itaque eos provident quisquam fugiat eius quae laborum laudantium explicabo fugit assumenda necessitatibus et cupiditate molestias eligendi natus deserunt officia. Ex.
    Numquam nobis inventore in error deleniti dolore commodi placeat. Iste voluptas illo numquam quos itaque, repellat deleniti dolore aperiam perferendis consectetur harum distinctio magni, explicabo molestias blanditiis, doloribus omnis nulla.
    Sint animi illo expedita harum voluptatum assumenda earum dolor adipisci in, praesentium accusantium impedit laudantium? Esse autem nihil fugit sunt optio quod iusto quaerat odio aspernatur, in rem, a soluta.
    Laboriosam esse perferendis similique quisquam rem suscipit nostrum distinctio. Beatae dicta soluta iure, voluptatum corporis, incidunt hic asperiores sint possimus ipsam animi. Nesciunt quas, libero est exercitationem animi beatae recusandae?
    Impedit eveniet laboriosam ad quia reprehenderit, eos dignissimos minus, nihil hic quasi, incidunt officiis dolorem nam maxime dicta veritatis velit praesentium quo saepe ipsa nisi accusantium? Alias qui natus iusto?
    Quam libero animi possimus inventore eos at quasi molestias expedita. Soluta ab, voluptatum ipsam consectetur eveniet qui officiis quibusdam accusantium cumque? Est hic dicta quos voluptates fuga nobis quod necessitatibus.
    Velit molestias fugiat ipsum, ad omnis maxime odio nam illo iure! Assumenda impedit nulla porro ex quas quod nihil voluptatem fuga magnam sit quia dolorem expedita, neque temporibus? Reiciendis, corrupti.
    At ipsum deserunt, illum sunt non recusandae ducimus facilis officiis maiores dolorum quidem similique minus sapiente eius sequi obcaecati officia eveniet enim. Fugit atque consequuntur molestiae maxime animi, nihil vitae?
    Iste, laudantium officiis id maxime ullam voluptatibus ea reprehenderit ipsa numquam distinctio ipsam illo quo, unde dolores mollitia, impedit voluptates iusto at amet omnis a quod hic. Laborum, dolore ipsa?</p>
<?php
$this->assets->outputJs();
?>