<h4>All Products</h4>

<br/>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Stock</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($result as $key => $value) {
        echo '<tr>
            <td>' . $value->name . '</td>
            <td>' . $value->category. '</td>
            <td>' . $value->price. '</td>
            <td>' . $value->stock. '</td>
            </tr>';
    }?>
    </tbody>
</table>
<br/>
<br/>
