<h4>All Products</h4>

<br />
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($result as $key => $value) {
            echo '<tr>
            <td>' . $value->name . '</td>
            <td>' . $value->category . '</td>
            <td>' . $value->price . '</td>
            <td>' . $value->stock . '</td>
            <td><a href="/admin/products/update/' . $value->_id . '">edit</a></td>
            <td><a href="/admin/products/delete/' . $value->_id . '">
            <button type="button"  class="btn-danger">delete</button>
            </a></td>
        </tr>';
        } ?>
    </tbody>
</table>
<br />
<br />

<?php
echo $this->tag->linkTo(
    '../admin/products/add',
    'Add more products!'
);
